title: Gold Star Mortgage Financial Video Blog
description: There is no such thing as a sad unicorn.

#for the navbar links.
custom_links:
  # - title: Luxury Properties
  #   url: http://www.sflivingspace.com/luxury-properties/

client:
  market:
  name: 'Gene Agustin & Bernie Tomei'
  brand: 'Gold Star Mortgage Financial Group<br>NMLS #3446'
  brokerage: '#'
  address: '5701 Lone Tree Blvd Ste 217<br>
Rocklin, CA 95765'
  phone: (408) 828-0575
  email: geneandbernie@gsfmail.com
  #Dont Include http://
  url: www.geneandbernie.com
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: 'http://www.geneandbernie.com/purchase-assistant/'
  homeeval_txt: Purchase Assistant
  homesearch: 'http://www.geneandbernie.com/refinance-advisor/'
  homesearch_txt: Refinance Advisor
  VR_form:

# social links
socials:
  facebook: 'https://www.facebook.com/GeneandBernie'
  linkedin: 'https://www.linkedin.com/in/bernie-sands-2aa0689'
  gplus: 'http://plus.google.com'
  youtube: 'http://youtube.com'
  twitter: 'http://twitter.com'
  instagram: '#'
  pinterest: '#'
  zillow: 'https://www.zillow.com/lender-profile/gagustin/'
  trulia: '#'
  yelp: 'https://www.yelp.com/biz/gene-agustin-and-bernie-tomei-rocklin-2'
  podcast: 'http://#.com'

#podcast settings
podcast:
  # Something Real Estate Podcast
  title:
  categories:
    - category: 'News &amp; Politics'
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --client brand-- - your professional --market-- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:

#layout options
# if we want review buttons --
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: /img/Sacramento_Skyline-1.jpg
  hero_logo_path: /img/Gold_Star_Mortgage_Financial_Logo.png
  hero_background_hex: '#f1dcb1'
  client_headshot_path: img/2016-09-26.png

#colors
brand_hex: '#2d306d'
theme_text: '#353535'
theme_color: '#fff'
fontcolor_hex: "#353535"
testimonial_fontcolor: '#fff'
