audit_header: false
title: Gold Star Mortgage Financial Video Blog
description: There is no such thing as a sad unicorn.
custom_links:
  - title:
    url:
client:
  name: 'Gene Agustin & Bernie Tomei'
  license:
  market:
  about_markdown: >
    'Founded in 2000 by Daniel Milstein, Gold Star is one of the nation’s
    premiere mortgage companies, doing business in 21 states, with over 30
    Branches nationwide.



    Gold Star is committed to delivering unsurpassed customer service to every
    borrower, corporate client and real estate professional. Our
    customer-focused, relationship-based sales model and commitment to continuous
    improvement of the loan process are keys to Gold Star’s continued growth.'
  brand: 'Gold Star Mortgage Financial Group<br>NMLS #3446'
  brokerage:
  address: '5701 Lone Tree Blvd Ste 217<br> Rocklin, CA 95765'
  phone: (408) 828-0575
  email: geneandbernie@gsfmail.com
  url: www.geneandbernie.com
  first_CTA_text: Purchase Assistant
  first_CTA_URL: 'http://www.geneandbernie.com/purchase-assistant/'
  second_CTA_text: Refinance Advisor
  second_CTA_URL: 'http://www.geneandbernie.com/refinance-advisor/'
  VR_form: 'http://oi.vresp.com?fid=4e18b36301'
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: >-
  We strive to provide a client experience that is unparalleled in our industry.
  Our love of family and passion for education are the foundation to our approach
  of creating an environment where honesty, diligence and communication are
  paramount.&nbsp; Using innovative technology and industry expertise we deliver
  a Gold Star experience.



  Subscribe to our blog to get the latest news on local market trends and receive
  expert tips for buying or selling a home.
socials:
  facebook_url: 'https://www.facebook.com/GeneandBernie'
  linkedin_url: 'https://www.linkedin.com/in/bernie-sands-2aa0689'
  gplus_url: 'http://plus.google.com'
  youtube_url: 'http://youtube.com'
  twitter_url: 'http://twitter.com'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/lender-profile/gagustin/'
  trulia_url:
  yelp_url: 'https://www.yelp.com/biz/gene-agustin-and-bernie-tomei-rocklin-2'
  podcast_url: 'http://#.com'
podcast:
  title:
  categories:
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --client brand-- - your professional --market-- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
review_sm_icons: false
images:
  hero_image_path: /img/Sacramento_Skyline-1.jpg
  hero_text:
  hero_logo_path: /img/Gold_Star_Mortgage_Financial_Logo.png
  hero_background_hex: '#f1dcb1'
  client_headshot_path: /img/2016-09-26.png
brand_color: '#2d306d'
theme_color: '#ffffff'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'