audit_header: false
title: Gold Star Mortgage Financial Video Blog
description: There is no such thing as a sad unicorn.
custom_links:
  - title:
    url:
client:
  name: Gene and Bernie – Your Trusted Mortgage Experts
  license:
  market:
  about_markdown: >-
    Welcome to Gold Star Mortgage Financial! We want to personally thank you for
    visiting us today and getting to know more about who we are and what we do.
    We have over 34 years combined mortgage lending experience and we work hard
    to get our clients the results they need.









    **OUR PHILOSOPHY**

    <br>There is an old saying that states, “If you love what you do, you will
    never work a day in your life”; we feel that saying was created just for us.
    Nothing is more fulfilling to us than helping people buy their first home,
    invest in real estate or save money! When you need a mortgage consultant that
    you can count on, do what thousands of others have already done, choose Gene
    and Bernie, and choose a successful future for yourself and your family.









    We work laterally with our clients every step of the way to ensure their
    needs are met while adhering to our high standards of excellence. If you want
    a team of professionals who listen and respond to your needs, trust us to
    show you what we can do for you today.









    **WHY CHOOSE US?**

    <br>Our team of experienced professionals strive to provide a higher level of
    service and support that our clients can’t get anywhere else. Our reputation
    speaks for itself; we offer a wide range of flexible and innovative financing
    solutions combined with our unparalleled service to create a mortgage
    solution that best suits your needs.









    From the initial consultation to the last details of the closing, we will be
    your consultant, your negotiator and your partner throughout the lending
    process.









    Your Real Estate Lending Resource for Life.
  brand: 'Gold Star Mortgage Financial Group<br>NMLS #3446'
  brokerage:
  address: '5701 Lone Tree Blvd Ste 217<br> Rocklin, CA 95765'
  phone: (408) 828-0575
  email: geneandbernie@gsfmail.com
  url: http://www.geneandbernie.com
  first_CTA_text: Purchase Assistant
  first_CTA_URL: 'http://www.geneandbernie.com/purchase-assistant/'
  second_CTA_text: Refinance Advisor
  second_CTA_URL: 'http://www.geneandbernie.com/refinance-advisor/'
  VR_form: 'http://oi.vresp.com?fid=4e18b36301'
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: >-
  We strive to provide a client experience that is unparalleled in our industry.
  Our love of family and passion for education are the foundation to our approach
  of creating an environment where honesty, diligence and communication are
  paramount.&nbsp; Using innovative technology and industry expertise we deliver
  a Gold Star experience.



  Subscribe to our blog to get the latest news on local market trends and receive
  expert tips for buying or selling a home.
socials:
  facebook_url: 'https://www.facebook.com/GeneandBernie'
  linkedin_url: 'https://www.linkedin.com/in/geneagustin'
  gplus_url: https://plus.google.com/112675116489876147825
  youtube_url: 'https://www.youtube.com/channel/UCclh-szkSD-_YddyDHnzbyw'
  twitter_url: 'https://twitter.com/GeneAgustin'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/lender-profile/gagustin/'
  trulia_url:
  yelp_url: 'https://www.yelp.com/biz/gene-agustin-and-bernie-tomei-rocklin-2'
  podcast_url: 'http://#.com'
podcast:
  title: Gold Star Mortgage Financial
  categories: News &amp; Politics
  image: http://i.imgur.com/vaCaq09.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --client brand-- - your professional --market-- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
review_sm_icons: false
images:
  hero_image_path: /img/Sacramento_Skyline-1.jpg
  hero_text:
  hero_logo_path: /img/Gold_Star_Mortgage_Financial_Logo.png
  hero_background_hex: '#f1dcb1'
  client_headshot_path: /img/2016-09-26.png
brand_color: '#2d306d'
theme_color: '#ffffff'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'